<?php

return [
    // ================= web menu =================
    'main' => [
        'M1' => [
            'name' => 'About',
            'route' => null,
            'param' => [],
            'url' => 'javascript:;',
            'blank' => false,
            'dev' => false,
            'continue' => false,
        ],

        'M2' => [
            'name' => 'Program',
            'route' => null,
            'param' => [],
            'url' => 'javascript:;',
            'blank' => false,
            'dev' => false,
            'continue' => false,
        ],

        'M3' => [
            'name' => 'Abstract',
            'route' => null,
            'param' => [],
            'url' => 'javascript:;',
            'blank' => false,
            'dev' => false,
            'continue' => false,
        ],

        'M4' => [
            'name' => 'Registration',
            'route' => null,
            'param' => [],
            'url' => 'javascript:;',
            'blank' => false,
            'dev' => false,
            'continue' => false,
        ],

        'M5' => [
            'name' => 'Accommodation',
            'route' => null,
            'param' => [],
            'url' => 'javascript:;',
            'blank' => false,
            'dev' => false,
            'continue' => false,
        ],

        'M6' => [
            'name' => 'Sponsorship',
            'route' => null,
            'param' => [],
            'url' => 'javascript:;',
            'blank' => false,
            'dev' => false,
            'continue' => false,
        ],

        'M7' => [
            'name' => 'Information',
            'route' => null,
            'param' => [],
            'url' => 'javascript:;',
            'blank' => false,
            'dev' => false,
            'continue' => false,
        ],

        'GUEST' => [
            'name' => 'Auth',
            'route' => 'login',
            'param' => [],
            'url' => null,
            'blank' => false,
            'dev' => false,
            'continue' => true,
        ],

        'MYPAGE' => [
            'name' => 'Mypage',
            'route' => 'mypage',
            'param' => [],
            'url' => null,
            'blank' => false,
            'dev' => false,
            'continue' => true,
        ],
    ],

    'sub' => [
        'M1' => [ // About
            'S1' => [
                'name' => 'Welcome Message',
                'route' => 'about.welcome',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],
            'S2' => [
                'name' => 'Committee',
                'route' => 'about.committee',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],
            'S3' => [
                'name' => 'Overview',
                'route' => 'about.overview',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],
            'S4' => [
                'name' => 'Contact Us',
                'route' => 'about.contact',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],
            'S5' => [
                'name' => 'News & Notice',
                'route' => 'board',
                'param' => ['code'=>'news'],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],
        ],
        'M2' => [ // PROGRAM
            'S1' => [
                'name' => 'Program at a Glance',
                'route' => 'program.glance',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],
            'S2' => [
                'name' => 'Scientific Program',
                'route' => 'program.scientific',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],
            'S3' => [
                'name' => 'Invited Speakers',
                'route' => 'program.speaker',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],
            'S4' => [
                'name' => 'Networking Events',
                'route' => 'program.event',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],
        ],
        'M3' => [ // Abstract
            'S1' => [
                'name' => 'Abstract Submission',
                'route' => 'abstract.submission',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],
            'S2' => [
                'name' => 'Awards',
                'route' => 'abstract.awards',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],
            'S3' => [
                'name' => 'Presentation Guidelines',
                'route' => 'abstract.guideline',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],
        ],
        'M4' => [ // Registration
            'S1' => [
                'name' => 'Registration Guideline',
                'route' => 'registration.guideline',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],
            'S2' => [
                'name' => 'Online Registration',
                'route' => 'registration.online',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],
            'S3' => [
                'name' => 'Visa',
                'route' => 'registration.visa',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],
        ],
        'M5' => [ // Accommodation
            'S1' => [
                'name' => 'Accommodation',
                'route' => 'accom.acc',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],
        ],
        'M6' => [ // Sponsorship
            'S1' => [
                'name' => 'Sponsorship Opportunities',
                'route' => 'sponsor.opp',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],
            'S2' => [
                'name' => 'Our Sponsors',
                'route' => 'sponsor.our',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],
        ],
        'M7' => [ // Information
            'S1' => [
                'name' => 'Venue',
                'route' => 'info.venue',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],
            'S2' => [
                'name' => 'Transportation',
                'route' => 'info.transportation',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],
            'S3' => [
                'name' => 'Tour Information',
                'route' => 'info.tour',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],
            'S4' => [
                'name' => 'Useful Information',
                'route' => 'info.useful',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],
            'S5' => [
                'name' => 'About Incheon',
                'route' => 'info.incheon',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],
            'S6' => [
                'name' => 'About Korea',
                'route' => 'info.korea',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],
        ],
        'GUEST' => [ // GUEST
            'S1' => [
                'name' => 'Login',
                'route' => 'login',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],

            'S2' => [
                'name' => 'Forgotten your ID?',
                'route' => 'auth.forget-id',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],

            'S3' => [
                'name' => 'Forgotten your password?',
                'route' => 'auth.forget-password',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],

            'S4' => [
                'name' => 'Sign-Up',
                'route' => 'auth.signup',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],
        ],

        'MYPAGE' => [ // 마이페이지
            'S1' => [
                'name' => 'Home',
                'route' => 'mypage',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],

            'S2' => [
                'name' => 'Personal Information',
                'route' => 'mypage.personal',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],

            'S3' => [
                'name' => 'Registration',
                'route' => 'mypage.registration',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],

            'S4' => [
                'name' => 'Abstract Submission',
                'route' => 'mypage.abstract',
                'param' => [],
                'url' => null,
                'blank' => false,
                'dev' => false,
                'continue' => false,
            ],
        ],
    ],
];
